=== pypi-data/pypi-mirror-19/packages/xml-archive-to-pdf/xml-archive-to-pdf-1.0.0.tar.gz/xml-archive-to-pdf-1.0.0/tests/data/pathfinder_v1.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="fr:unistra:di:archive:pathfinder:v1">
  <xs:element xmlns:unis="fr:unistra:di:archive:pathfinder:v1" name="personnage" type="unis:personnageType"/>
  <!-- Type nom -->
  <xs:complexType name="nomType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <!-- Type age -->
  <xs:complexType name="ageType">
    <xs:simpleContent>
      <xs:extension base="xs:byte">
        <xs:attribute type="xs:string" name="name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <!-- Type classe -->
  <xs:complexType name="classeType">
    <xs:sequence>
      <xs:element type="xs:string" name="nom"/>
      <xs:element type="xs:byte" name="niveau"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>
  <!-- Type classes -->
  <xs:complexType name="classesType">
    <xs:sequence>
      <xs:element xmlns:unis="fr:unistra:di:archive:pathfinder:v1" type="unis:classeType" name="classe" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>
  <!-- Type etat civil -->
  <xs:complexType name="etat-civilType">
    <xs:sequence>
      <xs:element xmlns:unis="fr:unistra:di:archive:pathfinder:v1" type="unis:nomType" name="nom"/>
      <xs:element xmlns:unis="fr:unistra:di:archive:pathfinder:v1" type="unis:ageType" name="age"/>
      <xs:element xmlns:unis="fr:unistra:di:archive:pathfinder:v1" type="unis:classesType" name="classes"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>
  <!-- Type personnage -->
  <xs:complexType name="personnageType">
    <xs:sequence>
      <xs:element xmlns:unis="fr:unistra:di:archive:pathfinder:v1" type="unis:etat-civilType" name="etat-civil"/>
    </xs:sequence>
    <xs:attribute type="xs:byte" name="id"/>
    <xs:attribute type="xs:string" name="source"/>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>
</xs:schema>

=== pypi-data/pypi-mirror-19/packages/xml-archive-to-pdf/xml-archive-to-pdf-1.0.0.tar.gz/xml-archive-to-pdf-1.0.0/tests/data/pathfinder_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Racine du fichier, id et source sont optionnels, le name correspond au titre -->
<personnage xmlns="fr:unistra:di:archive:pathfinder:v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="fr:unistra:di:archive:pathfinder:v1 pathfinder_v1.xsd"
    id="1" source="pathfinder" name="document récapitulatif du personnage 1 de pathfinder">
    <!-- Affiche le sous-titre de l'état civil -->
    <etat-civil name="son état civil">
        <!-- Affichage de clés/valeurs -->
        <nom>Sombre-crâne</nom>
        <age name="son âge">20</age>
        <!-- Nouveau bloc avec un sous-titre -->
        <classes name="classes et niveaux">
            <!-- Ici on affiche le sous-titre de name -->
            <classe name="Première classe">
                <nom>Barbare</nom>
                <niveau>3</niveau>
            </classe>
            <!-- Ici name est vide, donc ça affiche un titre vide -->
            <classe name="">
                <nom>Prêtre combattant</nom>
                <niveau>1</niveau>
            </classe>
            <!-- Lorsqu'il n'y a pas d'attribut name, on affiche le nom du tag. Ici classe -->
            <classe>
                <nom>Moine</nom>
                <niveau>2</niveau>
            </classe>
        </classes>
    </etat-civil>
</personnage>
